### ISSUE TITLE
Provisioning of the machine fails

### ISSUE THREAD

**Issue by oniric85** [FujiMakoto/IPS-Vagrant#14]
Hi,
I've tried a vagrant up today and it didn't end correctly. Instead I got this error:

```
==> default: Preparing to unpack .../mariadb-client-5.5_5.5.47-1ubuntu0.14.04.1_amd64.deb ...
==> default: De-configuring mariadb-server-5.5 (5.5.44-1ubuntu0.14.04.1) ...
==> default:  * Stopping MariaDB database server mysqld
==> default:    ...done.
==> default: Unpacking mariadb-client-5.5 (5.5.47-1ubuntu0.14.04.1) over (5.5.44-1ubuntu0.14.04.1) ...
==> default: Preparing to unpack .../mariadb-server-core-5.5_5.5.47-1ubuntu0.14.04.1_amd64.deb ...
==> default: Unpacking mariadb-server-core-5.5 (5.5.47-1ubuntu0.14.04.1) over (5.5.44-1ubuntu0.14.04.1) ...
==> default: Preparing to unpack .../multiarch-support_2.19-0ubuntu6.7_amd64.deb ...
==> default: Unpacking multiarch-support (2.19-0ubuntu6.7) over (2.19-0ubuntu6.6) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Errors were encountered while processing:
==> default:  /var/cache/apt/archives/mariadb-server-5.5_5.5.47-1ubuntu0.14.04.1_amd64.deb
==> default: Error in function:
==> default: SystemError
==> default: :
==> default: E:Sub-process /usr/bin/dpkg returned an error code (1)
==> default: Traceback (most recent call last):
==> default:   File "/usr/local/bin/ipsv", line 9, in <module>
==> default:
==> default: load_entry_point('IPS-Vagrant==0.4.1', 'console_scripts', 'ipsv')()
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
==> default:
==> default: return self.main(*args, **kwargs)
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
==> default:
==> default: rv = self.invoke(ctx)
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
==> default:
==> default: return _process_result(sub_ctx.command.invoke(sub_ctx))
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
==> default:
==> default: return ctx.invoke(self.callback, **ctx.params)
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
==> default:
==> default: return callback(*args, **kwargs)
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 63, in new_func
==> default:
==> default: return ctx.invoke(f, obj, *args[1:], **kwargs)
==> default:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
==> default:
==> default: return callback(*args, **kwargs)
==> default:   File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/commands/setup/__init__.py", line 64, in cli
==> default:
==> default: cache.commit()
==> default:   File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 505, in commit
==> default:
==> default: raise SystemError("installArchives() failed")
==> default: SystemError
==> default: :
==> default: installArchives() failed
```

The problem seems to arise during the system upgrade of all packages installed, specifically mariadb is causing some issues. I think this problem halts python init scripts so the machine after all is not correctly built.

**Comment by FujiMakoto** [comment]
You are on the right track, the issue is caused as Ubuntu is prompting you to upgrade from MySQL to MariaDB (which is halting the automated upgrades because it's requiring human input).

You can get around this for the time being by setting up a new box with **--no-provision**, booting into the box and running the upgrades normally, then rebooting with the **--provision** flag again.

**Comment by oniric85** [comment]
Thanks, with your suggestion I was able to provision the machine and use the ipsv tool correctly.
