### ISSUE TITLE
SSL error during dev tools download

### ISSUE THREAD

**Issue by oniric85** [FujiMakoto/IPS-Vagrant#15]
Hi,
I was trying to install a new site with dev tools enabled but installation halts with an error when dowloading the dev tools package. This is the complete error I get. It seems SSL/TLS related.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/downloaders/downloader.py", line 42, in _setup
    self._populate_latest()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/downloaders/dev_tools.py", line 60, in _populate_latest
    response = self.session.get(self.FILE_URL)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Traceback (most recent call last):
  File "/usr/local/bin/ipsv", line 9, in <module>
    load_entry_point('IPS-Vagrant==0.4.1', 'console_scripts', 'ipsv')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/commands/new/__init__.py", line 245, in cli
    i.start()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 88, in start
    self.system_check()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 111, in system_check
    self.license()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 131, in license
    self.applications()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 150, in applications
    self.server_details()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 202, in server_details
    self.admin()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 244, in admin
    self.install()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/latest.py", line 413, in install
    DevToolsInstaller(self.ctx, self.site).install()
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/installer/dev_tools/latest.py", line 33, in install
    status = p.OK if dev_tools.latest.request else p.FAIL
  File "/usr/local/lib/python2.7/dist-packages/ips_vagrant/downloaders/downloader.py", line 120, in latest
    return self.versions[next(reversed(self.versions))]
StopIteration
```

**Comment by FujiMakoto** [comment]
I noticed this a while back as well. I don't think I ever really found a good straightforward solution for the problem.

Supposedly the problem should resolve itself once the next box is built using the latest version of Ubuntu. The current OpenSSL library that Python is using does not properly support TLS (for reasons I cannot remember). community.invisionpower.com now only accept TLS based connections it seems and rejects SSLv2 or SSLv3 connections (which is actually a good standard security practice, the fact that TLS is not supported here is kind of ridiculous).

For the time being, if you don't pass the --dev and just set up IN_DEV manually it should avoid the issue for the time being.

**Comment by oniric85** [comment]
If I put the dev tools zip in the proper folder with the proper name, will the ipsv command pick it up? This would speed up future installations. Is yes, which is the proper name to assign to the zip file?

**Comment by FujiMakoto** [comment]
I found a quick temporary work-around which should resolve the issue. You just need to use a third party repository for python2.7 so you can upgrade to a version with SNI support,
```bash
sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get upgrade
```

**Comment by WillsB3** [comment]
I'm having this problem also. I tried running the 3 commands above but to no avail.

Any more pointers? I'm super new to Vagrant and IPS, so it's very likely I did something wrong.

I'm running on OS X 10.11.6
